"""Unit tests for Tabular ML annotation result format and validator compatibility."""

import pytest
from core.exceptions import BadRequestException
from modules.annotation.services.annotation_validator import AnnotationValidator
from modules.ontology.domain.entities import (
    CategoryEntity,
    OntologyEntity,
    OntologyOutputEntity,
    OntologyVersionEntity,
    OntologyVersionOutputCategoryEntity,
    OntologyVersionOutputEntity,
    OutputDefinitionEntity,
)


def _setup_tabular_ontology_version(output_type: str = "classification", value_schema: dict | None = None) -> OntologyVersionEntity:
    onto = OntologyEntity(project_id="proj_tabular", name="Tabular Fraud Detection")
    cat_legit = CategoryEntity(id="cat_legit", ontology_id=onto.id, key="legitimate", name="Legitimate")
    cat_fraud = CategoryEntity(id="cat_fraud", ontology_id=onto.id, key="fraud", name="Fraud")

    out_def = OutputDefinitionEntity(
        id=f"def_{output_type}",
        code=output_type,
        name=output_type.capitalize(),
        supports_categories=(output_type == "classification"),
        default_schema={},
    )

    out_entity = OntologyOutputEntity(
        id="out_tabular_target",
        ontology_id=onto.id,
        definition_id=out_def.id,
        name="Target",
        multiple=False,
        required=True,
        definition=out_def,
        value_schema=value_schema,
    )

    onto_ver = OntologyVersionEntity(
        id="ver_tabular_1",
        ontology_id=onto.id,
        version_no=1,
        name="v1.0",
        status="published",
    )

    categories = [
        OntologyVersionOutputCategoryEntity(
            ontology_version_id=onto_ver.id,
            ontology_output_id=out_entity.id,
            category_id=cat_legit.id,
            category=cat_legit,
        ),
        OntologyVersionOutputCategoryEntity(
            ontology_version_id=onto_ver.id,
            ontology_output_id=out_entity.id,
            category_id=cat_fraud.id,
            category=cat_fraud,
        ),
    ]

    link = OntologyVersionOutputEntity(
        ontology_version_id=onto_ver.id,
        ontology_output_id=out_entity.id,
        ontology_input_id="in_tabular",
        output=out_entity,
        categories=categories,
    )
    onto_ver.outputs = [link]
    return onto_ver


def test_tabular_record_labeling_format_validation():
    """Verify that row-level tabular records generated by TabularAnnotationWorkspace validate cleanly."""
    onto_ver = _setup_tabular_ontology_version()

    # Simulated results produced by annotating records 101 and 102
    results = [
        {
            "id": "rec_result__rec_00101",
            "output_id": "out_tabular_target",
            "result_type": "classification",
            "category_id": "cat_legit",
            "value": "cat_legit",
            "geometry": {
                "record_key": "rec_00101",
                "key_field": "transaction_id",
            },
            "created_at": "2026-09-27T12:00:00Z",
        },
        {
            "id": "rec_result__rec_00102",
            "output_id": "out_tabular_target",
            "result_type": "classification",
            "category_id": "cat_fraud",
            "value": "cat_fraud",
            "geometry": {
                "record_key": "rec_00102",
                "key_field": "transaction_id",
            },
            "created_at": "2026-09-27T12:00:05Z",
        },
    ]

    extracted_cats = AnnotationValidator.validate_results(results, onto_ver)
    assert set(extracted_cats) == {"cat_legit", "cat_fraud"}


def test_tabular_record_invalid_category_rejected():
    """Verify that assigning an unapproved category to a tabular record triggers validation error."""
    onto_ver = _setup_tabular_ontology_version()

    results = [
        {
            "id": "rec_result__rec_00101",
            "output_id": "out_tabular_target",
            "result_type": "classification",
            "category_id": "cat_unknown_fake",
            "value": "cat_unknown_fake",
            "geometry": {
                "record_key": "rec_00101",
                "key_field": "id",
            },
        }
    ]

    with pytest.raises(BadRequestException) as exc_info:
        AnnotationValidator.validate_results(results, onto_ver)
    assert "Category 'cat_unknown_fake' is not permitted" in str(exc_info.value)


def test_tabular_number_regression_with_schema():
    """Verify that numerical regression scoring on tabular rows conforms to value_schema."""
    value_schema = {
        "type": "number",
        "minimum": 0,
        "maximum": 100,
    }
    onto_ver = _setup_tabular_ontology_version(output_type="number", value_schema=value_schema)

    valid_results = [
        {
            "id": "rec_result__row_1",
            "output_id": "out_tabular_target",
            "result_type": "number",
            "value": 85.5,
            "geometry": {
                "record_key": "row_1",
                "key_field": "id",
            },
        }
    ]

    # Valid numeric score passes
    extracted = AnnotationValidator.validate_results(valid_results, onto_ver)
    assert extracted == []

    # Out of range numeric score raises error
    invalid_results = [
        {
            "id": "rec_result__row_1",
            "output_id": "out_tabular_target",
            "result_type": "number",
            "value": 150.0,
            "geometry": {
                "record_key": "row_1",
                "key_field": "id",
            },
        }
    ]
    with pytest.raises(BadRequestException):
        AnnotationValidator.validate_results(invalid_results, onto_ver)


def test_tabular_cell_legacy_compatibility():
    """Verify that legacy cell-level annotations (table_cell) are preserved without breaking validator."""
    onto_ver = _setup_tabular_ontology_version()

    results = [
        {
            "id": "table_0_age",
            "output_id": "out_tabular_target",
            "result_type": "table_cell",
            "category_id": "cat_legit",
            "geometry": {
                "row": 0,
                "col_name": "age",
                "value": "25",
            },
        },
        {
            "id": "rec_result__rec_001",
            "output_id": "out_tabular_target",
            "result_type": "classification",
            "category_id": "cat_fraud",
            "geometry": {
                "record_key": "rec_001",
                "key_field": "id",
            },
        },
    ]

    extracted = AnnotationValidator.validate_results(results, onto_ver)
    assert set(extracted) == {"cat_legit", "cat_fraud"}
