from collections.abc import Sequence
from typing import Protocol

from modules.ontology.domain.entities import (
    CategoryEntity,
    InputDefinitionEntity,
    OntologyEntity,
    OntologyInputEntity,
    OntologyOutputEntity,
    OntologyVersionEntity,
    OntologyVersionInputEntity,
    OntologyVersionOutputEntity,
    OutputDefinitionEntity,
)


class IOntologyRepository(Protocol):
    async def add(self, entity: OntologyEntity) -> OntologyEntity: ...
    async def get(self, entity_id: str) -> OntologyEntity | None: ...
    async def get_by_project(self, project_id: str) -> OntologyEntity | None: ...
    async def list_by_project(self, project_id: str) -> Sequence[OntologyEntity]: ...
    async def update(self, entity: OntologyEntity) -> OntologyEntity: ...
    async def delete(self, entity_id: str) -> bool: ...
    async def has_published_version(self, entity_id: str) -> bool: ...
    async def get_version_by_id(
        self, version_id: str
    ) -> OntologyVersionEntity | None: ...


class IInputDefinitionRepository(Protocol):
    async def add(self, entity: InputDefinitionEntity) -> InputDefinitionEntity: ...
    async def get(self, entity_id: str) -> InputDefinitionEntity | None: ...
    async def list(self) -> Sequence[InputDefinitionEntity]: ...
    async def update(self, entity: InputDefinitionEntity) -> InputDefinitionEntity: ...
    async def delete(self, entity_id: str) -> bool: ...
    async def is_used(self, entity_id: str) -> bool: ...


class IOutputDefinitionRepository(Protocol):
    async def add(self, entity: OutputDefinitionEntity) -> OutputDefinitionEntity: ...
    async def get(self, entity_id: str) -> OutputDefinitionEntity | None: ...
    async def list(self) -> Sequence[OutputDefinitionEntity]: ...
    async def update(
        self, entity: OutputDefinitionEntity
    ) -> OutputDefinitionEntity: ...
    async def delete(self, entity_id: str) -> bool: ...
    async def is_used(self, entity_id: str) -> bool: ...


class IOntologyInputRepository(Protocol):
    async def add(self, entity: OntologyInputEntity) -> OntologyInputEntity: ...
    async def get(self, entity_id: str) -> OntologyInputEntity | None: ...
    async def list_by_ontology(
        self, ontology_id: str
    ) -> Sequence[OntologyInputEntity]: ...
    async def update(self, entity: OntologyInputEntity) -> OntologyInputEntity: ...
    async def delete(self, entity_id: str) -> bool: ...
    async def is_locked(self, entity_id: str) -> bool: ...


class IOntologyOutputRepository(Protocol):
    async def add(self, entity: OntologyOutputEntity) -> OntologyOutputEntity: ...
    async def get(self, entity_id: str) -> OntologyOutputEntity | None: ...
    async def list_by_ontology(
        self, ontology_id: str
    ) -> Sequence[OntologyOutputEntity]: ...
    async def update(self, entity: OntologyOutputEntity) -> OntologyOutputEntity: ...
    async def delete(self, entity_id: str) -> bool: ...
    async def is_locked(self, entity_id: str) -> bool: ...


class ICategoryRepository(Protocol):
    async def add(self, entity: CategoryEntity) -> CategoryEntity: ...
    async def get(self, entity_id: str) -> CategoryEntity | None: ...
    async def list_by_ontology(self, ontology_id: str) -> Sequence[CategoryEntity]: ...
    async def get_by_key(self, ontology_id: str, key: str) -> CategoryEntity | None: ...
    async def update(self, entity: CategoryEntity) -> CategoryEntity: ...
    async def delete(self, entity_id: str) -> bool: ...
    async def is_locked(self, entity_id: str) -> bool: ...


class IOntologyVersionRepository(Protocol):
    async def add(self, entity: OntologyVersionEntity) -> OntologyVersionEntity: ...
    async def get(self, entity_id: str) -> OntologyVersionEntity | None: ...
    async def list_by_ontology(
        self, ontology_id: str
    ) -> Sequence[OntologyVersionEntity]: ...
    async def update(self, entity: OntologyVersionEntity) -> OntologyVersionEntity: ...
    async def replace_composition(
        self,
        version_id: str,
        inputs: Sequence[OntologyVersionInputEntity],
        outputs: Sequence[OntologyVersionOutputEntity],
    ) -> OntologyVersionEntity: ...
    async def delete(self, entity_id: str) -> bool: ...
    async def next_version_no(self, ontology_id: str) -> int: ...
    async def get_draft(self, ontology_id: str) -> OntologyVersionEntity | None: ...
