"""add raw_label_config to ontology versions

Revision ID: 5424e25876cf
Revises: '006_add_label_studio_task_id'
Create Date: 2026-07-29 13:01:13.789809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5424e25876cf'
down_revision: Union[str, None] = '006_add_label_studio_task_id'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ontology_versions', sa.Column('raw_label_config', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ontology_versions', 'raw_label_config')
    # ### end Alembic commands ###
